beyond-sw-camp/be04-final-team06-ERPC

Backend/erpc/build.gradle
Backend/erpc/src/main/java/com/cineverse/erpc/employee/aggregate/Employee.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/dto/EmployeeDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/security/AuthenticationFilter.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/service/EmployeeService.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/service/EmployeeServiceImpl.java

- JWT 토큰 발급 후 Header에 토큰을 담아 전달

[PR] 로그인 기능 수정

---

Backend/erpc/src/main/java/com/cineverse/erpc/employee/security/WebSecurity.java
Backend/erpc/src/main/java/com/cineverse/erpc/notice/board/service/NoticeBoardService.java
Backend/erpc/src/main/java/com/cineverse/erpc/notice/comment/aggregate/entity/NoticeComment.java
Backend/erpc/src/main/java/com/cineverse/erpc/notice/comment/aggregate/entity/NoticeCommentEntity.java
Backend/erpc/src/main/java/com/cineverse/erpc/notice/comment/controller/NoticeCommentController.java
Backend/erpc/src/main/java/com/cineverse/erpc/notice/comment/dto/NoticeCommentDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/notice/comment/repository/NoticeCommentRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/notice/comment/service/NoticeCommentService.java
Backend/erpc/src/main/java/com/cineverse/erpc/notice/comment/service/NoticeCommentServiceImpl.java
Frontend/erpc/src/components/order/OrderRegist.vue

공지사항 게시글 작성, 수정, 삭제, 전체 조회, 단일 조회 기능 구현 완료
공지사항 댓글 작성, 삭제, 전체 조회 기능 구현 완

[PR] 공지사항 및 공지사항 댓글 기능 구현 완료

---

Backend/erpc/src/main/java/com/cineverse/erpc/contract/aggregate/Contract.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/aggregate/ContractProduct.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/dto/ContractDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/repository/ContractProductRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/service/ContractServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/quotation/quotation/aggregate/Quotation.java
Backend/erpc/src/main/java/com/cineverse/erpc/quotation/quotation/service/QuotationServiceImpl.java
Frontend/erpc/src/App.vue
Frontend/erpc/src/assets/css/customer/CustomerContents.css
Frontend/erpc/src/assets/css/performance/TeamPerformance.css
Frontend/erpc/src/assets/css/performance/YearPerformance.css
Frontend/erpc/src/components/customer/CustomerContents.vue
Frontend/erpc/src/components/performance/TeamPerformance.vue
Frontend/erpc/src/components/performance/YearPerformance.vue

1. 견적서 생성 시 중간객체가 quotationId를 인식하지 못하는 오류 수정
2. 견적서 수정 시 quotationProduct 업데이트가 재대로 되지 않는 오류 수정

[PR] 견적서 오류 수정

---

Backend/erpc/src/main/java/com/cineverse/erpc/order/order/controller/OrderController.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/dto/RequestModifyOrder.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/dto/ResponseModifyOrder.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/repo/OrderProductRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/service/OrderService.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/service/OrderServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/target/aggregate/TargetType.java

어떤 변경 사항이 있나요?
PR이 다음 요구 사항을 충족하는지 확인하세요.

[PR] 수주 수정

---

Backend/erpc/src/main/java/com/cineverse/erpc/target/controller/TargetController.java
Backend/erpc/src/main/java/com/cineverse/erpc/target/repository/TargetRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/target/service/TargetService.java
Backend/erpc/src/main/java/com/cineverse/erpc/target/service/TargetServiceImpl.java

개인별, 팀별, 통합 실적 조회 기능 구현 완료
(월별, 분기별, 연도별 개인+팀+통합 조회 기능 구현 완료)

[PR] 실적 조회 기능 구현

---

Backend/erpc/src/main/java/com/cineverse/erpc/order/note/aggregate/OrderNote.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/note/controller/OrderNoteController.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/note/dto/RequestRegistOrderNoteDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/note/dto/ResponseFindOrderNotesDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/note/dto/ResponseRegistOrderNoteDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/note/repo/OrderNoteRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/note/service/OrderNoteService.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/note/service/OrderNoteServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/service/OrderServiceImpl.java

어떤 변경 사항이 있나요?
PR이 다음 요구 사항을 충족하는지 확인하세요.

[PR] 수주 참고사항

---

Backend/erpc/src/main/java/com/cineverse/erpc/config/TransactionConfig.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/controller/ContractController.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/service/ContractServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/security/WebSecurity.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/collection/aggregate/Collection.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/collection/aggregate/DepositCategory.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/collection/controller/CollectionController.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/collection/dto/CollectionDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/collection/repository/CollectionRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/collection/service/CollectionService.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/collection/service/CollectionServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/aggreagte/TaxInvoiceFile.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/aggreagte/TaxInvoiceProcess.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/aggreagte/TaxInvoiceRequest.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/aggreagte/TaxInvoiceRequestStatus.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/controller/TaxInvoiceController.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/dto/TaxInvoiceFileDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/dto/TaxInvoiceProcessDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/dto/TaxInvoiceRequestDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/repository/TaxInvoiceRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/service/TaxInvoiceService.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/service/TaxInvoiceServiceImpl.java

[PR] 수금 조회

---

Backend/erpc/src/main/java/com/cineverse/erpc/contract/repository/ContractProductRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/service/ContractServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/quotation/quotation/service/QuotationServiceImpl.java
Frontend/erpc/src/App.vue
Frontend/erpc/src/assets/css/bill/CBList.css
Frontend/erpc/src/assets/css/bill/CBRequest.css
Frontend/erpc/src/assets/css/customer/CustomerContents.css
Frontend/erpc/src/assets/css/customer/CustomerList.css
Frontend/erpc/src/assets/css/order/OrderContents.css
Frontend/erpc/src/assets/css/order/OrderList.css
Frontend/erpc/src/assets/css/order/OrderRegist.css
Frontend/erpc/src/components/customer/CustomerContents.vue
Frontend/erpc/src/components/customer/CustomerRegist.vue
Frontend/erpc/src/components/logistics/ItemList.vue
Frontend/erpc/src/components/logistics/StorageList.vue
Frontend/erpc/src/components/order/OrderContents.vue
Frontend/erpc/src/components/salesopp/SalesOppContent.vue
Frontend/erpc/src/components/salesopp/SalesOppList.vue
Frontend/erpc/src/components/salesopp/SalesOppRegist.vue

계약서 수정 기능 develop
계약서 수정 시 품목 수정 시 기존 품목 전체 품목 삭제 후 재등록 기능 구현 완료

[PR] 계약서 수정 

---

Backend/erpc/src/main/java/com/cineverse/erpc/access/controller/AccessController.java
Backend/erpc/src/main/java/com/cineverse/erpc/access/dto/RequestAddAccessDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/access/dto/ResponseAddAccessDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/access/repo/EmployeeAccessRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/access/service/AccessService.java
Backend/erpc/src/main/java/com/cineverse/erpc/access/service/AccessServiceImpl.java

1. 여러개의 권한을 한번에 부여하는 경우 해결
2. 기존에 존재하던 권한을 삭제하고 새로운 권한 insert 함.
Resolves: #26

[PR] fix: 권한부여

---

Backend/erpc/src/main/java/com/cineverse/erpc/salesopp/opportunity/aggregate/SalesOpp.java

delete branch new

---

Backend/erpc/src/main/java/com/cineverse/erpc/salesopp/opportunity/aggregate/SalesOpp.java

delete branch push

---

Backend/erpc/src/main/java/com/cineverse/erpc/approval/service/ApprovalServiceImpl.java

1. 수주 결재 단일 조회 구현
Resolves: #82
수주 결재 단일 조회 구현
- 결재 조회 구현 완료
Resolves: #82

[PR] 결재 조회

---

Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/controller/DeleteController.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/service/DeleteService.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/service/DeleteServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/aggregate/ContractDeleteRequest.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/controller/ContractController.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/dto/ContractDeleteRequestDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/repository/ContractDeleteRequestRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/service/ContractService.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/service/ContractServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/salesopp/opportunity/aggregate/SalesOppDeleteRequest.java
Backend/erpc/src/main/java/com/cineverse/erpc/salesopp/opportunity/dto/SalesOppDeleteRequestDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/salesopp/opportunity/repository/SalesOppDeleteRequestRepository.java

1. 계약서 삭제 요청
2. 계약서 삭제 요청 내역 전체조회
3. 계약서 삭제 요청 내역 단일조회
4. 계약서 삭제 처리
#52

[PR] 계약서 삭제요청

---

Backend/erpc/src/main/java/com/cineverse/erpc/employee/controller/EmployeeController.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/dto/RequestModifyPassword.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/dto/RequestRegistDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/dto/ResponseModifyPassword.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/service/EmployeeService.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/service/EmployeeServiceImpl.java

- 비밀번호 재설정
- 비밀번호 재설정 후 암호화 적용

[PR] 비밀번호 재설정

---

Backend/.idea/.gitignore
Backend/erpc/src/main/java/com/cineverse/erpc/contract/controller/ContractController.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/repository/ContractRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/service/ContractService.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/service/ContractServiceImpl.java

[PR] 계약서 조회

---

Backend/erpc/src/main/java/com/cineverse/erpc/account/account/aggregate/AccountDeleteRequest.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/account/controller/AccountController.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/account/dto/RequestDeleteAccount.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/account/dto/ResponseDeleteAccount.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/account/repository/AccountDeleteRequestRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/account/service/AccountService.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/account/service/AccountServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/controller/DeleteController.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/dto/account/RequestAccountDeleteRequestProcess.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/dto/account/ResponseAccountDeleteRequestList.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/dto/account/ResponseAccountDeleteRequestProcess.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/dto/account/ResponseFindAccoundDeleteRequest.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/service/DeleteService.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/service/DeleteServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/quotation/quotation/aggregate/QuotationDeleteRequest.java

- [v] 기능개발(Feature)
- 거래처 삭제요청 구현 완료
- 거래처 삭제요청 단일조회
- 거래처 삭제요청 전체 조회
- 거래처 삭제요청 처리
- Resolves: #34

[PR] 거래처 삭제요청

---

Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/service/DeleteServiceImpl.java

- 거래처 삭제일자 변경
- 거래처 삭제 처리시 삭제일자 업데이트

[PR] 거래처 삭제일자 수정

---

Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/service/DeleteServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/salesopp/opportunity/aggregate/SalesOppDeleteRequest.java
Backend/erpc/src/main/java/com/cineverse/erpc/salesopp/opportunity/dto/SalesOppDeleteRequestDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/salesopp/opportunity/service/SalesOppServiceImpl.java

영업기회 삭제 요청 DB 수정
영업기회 삭제 요청 테이블 db 수정

[PR] 영업기회 삭제요청

---

Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/controller/DeleteController.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/dto/order/RequestOrderDeleteRequestProcess.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/dto/order/ResponseFindOrderDeleteRequest.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/dto/order/ResponseOrderDeleteRequestList.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/dto/order/ResponseOrderDeleteRequestProcess.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/service/DeleteService.java
Backend/erpc/src/main/java/com/cineverse/erpc/admin/delete/service/DeleteServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/aggregate/OrderDeleteRequest.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/controller/OrderController.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/dto/RequestDeleteOrder.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/dto/ResponseDeleteOrder.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/repo/OrderDeleteRequestRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/service/OrderService.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/service/OrderServiceImpl.java

- 수주 삭제요청
1. 삭제요청 생성
2. 삭제요청 조회(단일, 전체)
3. 삭제요청 처리
- Resovles: #61

[PR] 수주 삭제요청

---

Backend/erpc/src/main/java/com/cineverse/erpc/contract/service/ContractServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/quotation/quotation/service/QuotationServiceImpl.java
Frontend/erpc/src/assets/css/bill/CBRequest.css
Frontend/erpc/src/assets/css/bill/Deposit.css
Frontend/erpc/src/assets/css/contract/ContractList.css
Frontend/erpc/src/assets/css/customer/CustomerList.css
Frontend/erpc/src/assets/css/estimate/EstimateList.css
Frontend/erpc/src/assets/css/order/OrderList.css

css 수정 및 로그인 문제 해결

---

Backend/erpc/src/main/java/com/cineverse/erpc/account/account/dto/RequestDeleteAccount.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/account/dto/ResponseDeleteAccount.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/account/service/AccountService.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/account/service/AccountServiceImpl.java
Backend/erpc/src/test/java/com/cineverse/erpc/account/AccountTests.java

- 거래처 테스트
1. 거래처 생성 성공 테스트
2. 거래처 단일조회 성공 테스트
3. 거래처 전체조회 성공 테스트
4. 거래처 수정 성공 테스트
5. 거래처 삭제요청 성공 테스트
Resolves: #36

Account test

---

Backend/erpc/src/main/java/com/cineverse/erpc/account/note/controller/AccountNoteController.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/note/dto/RequestAccountNoteRegistDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/note/dto/ResponseAccountNoteRegistDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/note/dto/ResponseDeleteAccountNote.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/note/service/AccountNoteService.java
Backend/erpc/src/main/java/com/cineverse/erpc/account/note/service/AccountNoteServiceImpl.java
Backend/erpc/src/test/java/com/cineverse/erpc/account/account/AccountTests.java
Backend/erpc/src/test/java/com/cineverse/erpc/account/note/AccountNoteTests.java

- 거래처 참고사항 테스트코드 작성
- 거래처 참고사항 삭제 기능 추가
- 거래처 참고사항 전체 조회 성공 테스트
- 거래처 참고사항 등록 성공 테스트
- 거래처 참고사항 삭제 성공 테스트

[PR] 거래처 테스트

---

Backend/erpc/src/main/java/com/cineverse/erpc/contract/controller/ContractController.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/service/ContractService.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/service/ContractServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/file/repository/ContractFileRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/file/service/FileUploadService.java

계약서 수정 시 기존 파일 삭제 후 파일 재등록 기능 구현 완료
1. 파일 수정 시 업로드 된 기존 파일 일괄 삭제
2. 파일 수정 시 파일 신규 등록 가능

[PR] 파일 업로드

---

Backend/erpc/src/main/java/com/cineverse/erpc/file/repository/TaxInvoiceFileRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/file/service/FileUploadService.java

[PR] 세금계산서 요청 파일 삭제

---

Backend/erpc/src/main/java/com/cineverse/erpc/contract/controller/ContractController.java

Bug: git merge error fix try

---

Backend/erpc/build.gradle

Create: build.gradle add

---

Backend/erpc/src/main/java/com/cineverse/erpc/approval/dto/contract/RequestContractApprovalProcess.java
Backend/erpc/src/main/java/com/cineverse/erpc/approval/dto/contract/RequestRegistContractApproval.java
Backend/erpc/src/main/java/com/cineverse/erpc/approval/dto/quotation/RequestQuotationApprovalProcess.java
Backend/erpc/src/main/java/com/cineverse/erpc/approval/dto/quotation/RequestRegistQuotationApproval.java
Backend/erpc/src/main/java/com/cineverse/erpc/approval/dto/shipment/RequestRegistShipmentApproval.java
Backend/erpc/src/main/java/com/cineverse/erpc/approval/dto/shipment/RequestShipmentApprovalProcess.java
Backend/erpc/src/test/java/com/cineverse/erpc/approval/ApprovalTests.java

- 결재 테스트
1. 결재 처리 성공 테스트
2. 결재 단일 조회 성공 테스트
3. 결재 전체 조회 성공 테스트
4. 결재 등록 성공 테스트
Resolves: #84

[PR]Approval test

---

Backend/erpc/src/main/java/com/cineverse/erpc/contract/controller/ContractController.java
Backend/erpc/src/main/java/com/cineverse/erpc/notice/board/controller/NoticeBoardController.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/controller/OrderController.java
Backend/erpc/src/main/java/com/cineverse/erpc/quotation/quotation/controller/QuotationController.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/controller/TaxInvoiceController.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/repository/TaxInvoiceRequestRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/service/TaxInvoiceServiceImpl.java

파일 업로드 시 인코딩 오류 해결
공지사항, 견적서, 계약서, 수주, 세금계산서 요청

[PR] Encoding Error

---

Backend/erpc/src/main/java/com/cineverse/erpc/order/order/dto/RequestDeleteOrder.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/dto/RequestModifyOrder.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/dto/RequestRegistOrderDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/dto/ResponseModifyOrder.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/dto/ResponseRegistOrderDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/service/OrderService.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/service/OrderServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/quotation/quotation/aggregate/Quotation.java
Backend/erpc/src/main/java/com/cineverse/erpc/quotation/quotation/dto/RequestRegistQuotationDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/quotation/quotation/service/QuotationService.java
Backend/erpc/src/main/java/com/cineverse/erpc/quotation/quotation/service/QuotationServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/shipment/repo/ShipmentRepository.java
Backend/erpc/src/test/java/com/cineverse/erpc/account/order/OrderTests.java

- 수주 테스트코드 작성
- 수주 단일조회 성공 테스트
- 수주 전체조회 성공 테스트
- 수주 생성 성공 테스트
- 수주 수정 성공 테스트
- 수주 삭제요청 성공 테스트
#65

[PR] 수주 테스트

---

Backend/erpc/src/main/java/com/cineverse/erpc/notice/board/controller/NoticeBoardController.java
Backend/erpc/src/main/java/com/cineverse/erpc/notice/board/service/NoticeBoardServiceImpl.java
Backend/erpc/src/test/java/com/cineverse/erpc/notice/NoticeBoardControllerTests.java
Backend/erpc/src/test/java/com/cineverse/erpc/notice/NoticeCommentControllerTests.java
Backend/erpc/src/test/java/com/cineverse/erpc/notice/board/controller/NoticeBoardControllerTests.java

1. 공지사항 등록 테스트
2. 공지사항 수정 테스트
3. 공지사항 삭제 테스트
4. 공지사항 전체조회 테스트
5. 공지사항 단일조회 테스트

[PR] 공지사항 테스트

---

Backend/erpc/src/main/java/com/cineverse/erpc/employee/aggregate/Employee.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/aggregate/EmployeeRank.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/aggregate/TeamCode.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/controller/EmployeeController.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/dto/EmployeeDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/dto/RequestModifyEmployee.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/dto/RequestModifyPassword.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/dto/RequestRegistDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/dto/ResponseEmployeeDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/dto/ResponseEmployeesDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/dto/ResponseModifyEmployee.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/dto/ResponseRegistDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/service/EmployeeService.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/service/EmployeeServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/notice/board/aggregate/NoticeBoard.java
Backend/erpc/src/main/java/com/cineverse/erpc/notice/board/dto/NoticeBoardDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/repo/OrderRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/sales/service/SalesServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/target/aggregate/Target.java
Backend/erpc/src/main/java/com/cineverse/erpc/target/dto/TargetDTO.java
Backend/erpc/src/test/java/com/cineverse/erpc/employee/EmployeeTests.java
Backend/erpc/src/test/java/com/cineverse/erpc/order/note/OrderNoteTests.java
Backend/erpc/src/test/java/com/cineverse/erpc/order/order/OrderTests.java

- 사원 관련 테스트
- 비밀번호 암호화 관련 테스트
- 사원 정보수정 기능 추가
- 패키지 위치 변경
1. 사원 생성 성공 테스트
2. 사원 단일조회 성공 테스트
3. 사원 전체조회 성공 테스트
4. 사원 비밀번호 변경 성공 테스트
5. 사원 정보수정 성공 테스트
6. 사원 정보수정 기능 추가
7. 사원 엔티티 수정(팀코드, 직급)
8. 수주 패키지 이동
#18, #25

[PR] 사원 테스트

---

Backend/erpc/src/main/java/com/cineverse/erpc/employee/repo/TeamRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/sales/controller/SalesController.java
Backend/erpc/src/test/java/com/cineverse/erpc/notice/NoticeBoardControllerTests.java
Backend/erpc/src/test/java/com/cineverse/erpc/sales/SalesControllerTests.java

1. 개인별 매출 조회
2. 팀별 매출 조회
3. 통합 매출 조회

[PR] 매출 테스트

---

Backend/erpc/src/main/java/com/cineverse/erpc/target/service/TargetServiceImpl.java
Backend/erpc/src/test/java/com/cineverse/erpc/target/controller/TargetControllerTests.java

1. 개인별 목표 실적 조회
2. 팀별 목표 실적 조회
3. 통합 목표 실적 조회

[PR] 목표 실적 조회

---

Backend/erpc/src/main/java/com/cineverse/erpc/sales/service/SalesServiceImpl.java
Backend/erpc/src/test/java/com/cineverse/erpc/sales/SalesControllerTests.java

[PR]Refactor 매출 실적 조회

---

Backend/erpc/src/test/java/com/cineverse/erpc/product/ProductControllerTests.java
Backend/erpc/src/test/java/com/cineverse/erpc/warehouse/WarehouseControllerTests.java

1. 품목 전체 조회
2. 품목 단일 조회
3. 창고 전체 조회

Test: 품목/창고 테스트

---

Backend/erpc/src/main/java/com/cineverse/erpc/contract/dto/ContractDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/dto/ContractProductDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/repository/ContractRepository.java
Backend/erpc/src/main/java/com/cineverse/erpc/contract/service/ContractServiceImpl.java
Backend/erpc/src/main/java/com/cineverse/erpc/employee/security/WebSecurity.java
Backend/erpc/src/main/java/com/cineverse/erpc/excel/controller/ContractExcelController.java
Backend/erpc/src/main/java/com/cineverse/erpc/excel/controller/ExcelController.java
Backend/erpc/src/main/java/com/cineverse/erpc/excel/controller/ExcelTest.java
Backend/erpc/src/main/java/com/cineverse/erpc/excel/controller/OrderExcelController.java
Backend/erpc/src/main/java/com/cineverse/erpc/excel/controller/QuotationExcelController.java
Backend/erpc/src/main/resources/excel.html

1. 단일 계약서 엑셀 형식 변환 및 다운로드 기능 구현 완료
2. 관련 코드 수정 및 리팩토링

[PR] 엑셀 파일 변환

---

Backend/erpc/src/test/java/com/cineverse/erpc/product/ProductControllerTests.java
Backend/erpc/src/test/java/com/cineverse/erpc/warehouse/WarehouseControllerTests.java

1. 품목 전체조회 테스트코드 수정
2. 창고 전체조회 테스트코드 수정

[PR] 품목/창고 테스트

---

Backend/erpc/src/main/java/com/cineverse/erpc/slip/collection/controller/CollectionController.java
Backend/erpc/src/test/java/com/cineverse/erpc/slip/collection/CollectionControllerTests.java
Backend/erpc/src/test/java/com/cineverse/erpc/slip/taxinvoice/TaxInvoiceControllerTests.java

[PR] 수금 테스트

---

Backend/erpc/src/test/java/com/cineverse/erpc/slip/CollectionControllerTests.java
Backend/erpc/src/test/java/com/cineverse/erpc/slip/TaxInvoiceControllerTests.java

- [x] 리팩토링 (no functional changes, no api changes)
수금 및 세금계산서 controllerTest refactor

[PR] 전표 테스트

---

Backend/erpc/build.gradle
Backend/erpc/src/main/java/com/cineverse/erpc/file/aggregate/TaxInvoiceFile.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/aggregate/Order.java
Backend/erpc/src/main/java/com/cineverse/erpc/order/order/dto/OrderDTO.java
Backend/erpc/src/main/java/com/cineverse/erpc/slip/taxinvoice/aggreagte/TaxInvoiceRequest.java

1. 수주 단일 조회 시 해당 된 수주로 요청한 세금계산서 조회

[PR] Order

---

README.md

readme merge

---

eprc-back/src/main/java/com/cineverse/erpc/employee/security/WebSecurity.java
eprc-back/src/main/java/com/cineverse/erpc/redis/controller/RedisSingleDataController.java
eprc-back/src/main/java/com/cineverse/erpc/redis/service/RedisSingleDataService.java
eprc-back/src/main/java/com/cineverse/erpc/redis/service/RedisSingleDataServiceImpl.java

1. security 경로 추가(redis)
2. controller 중복 메소드 삭제
3. service 패키지 명 변경, impl 패키지명 변경

Feat: Redis

---

eprc-back/build.gradle
eprc-back/src/main/java/com/cineverse/erpc/aop/LogAspect.java
eprc-back/src/main/java/com/cineverse/erpc/aop/LogExecutionTime.java

1. AOP 의존성 추가
2. LogExecutionTime 추가
3. LogAspect 추가

25.01.09 메소드 시간 체크
